### ISSUE TITLE
Overflow-x: hidden on html and body causes protip not to show up when scrolled

### ISSUE THREAD

**Issue by zenichanin** [wintercounter/Protip#21]
I think this is a bug.  If I add `overflow-x: hidden` to my CSS and I have protips that go beyond the top fold of the page, the bottom protips show up but in their original non-scrolled location and thus can't even be seen on the screen.

Here's an example and if you scroll down in render area and hover over any of the Tip words near the bottom of page, you won't see a protip:
https://jsfiddle.net/ouamhaw9/4/

And here it works when I comment out `overflow-x: hidden`:
https://jsfiddle.net/ouamhaw9/5/

**Comment by wintercounter** [comment]
Seems like this is a Chrome bug. If overflow-x is applied **both** to html and body, Chrome will report `document.body.scrollTop` to be 0. It's a known bug. If you remove overflow-x only from the html element, it'll work just fine. Te be honest I don't know how should I fix this without having proper metrics, it even breaks jQuery also :( I leave this issue open so anyone with the same issue can see this, but no fix will be done by me.

https://jsfiddle.net/4frs821y/
https://github.com/jquery/jquery/issues/2215#issuecomment-94332101

**Comment by zenichanin** [comment]
Ahh ok.  I'll just use it on the body element and hope Chrome will get fixed over time.  Thanks for the help.

**Comment by Tofandel** [comment]
So I had a look and... in the _getPosition function the document.body.scrollTop is actually not included in the calculation while it should be.. Also the gravity feature is not updating the top position of the item while it also should.

**Comment by wintercounter** [comment]
This is a weird situation. When you apply the `overflow-x: hidden` both on `html` and `body`, the scroll element becomes the `body`. In a normal situation however the scroll element is `window`. You can test by adding both listeners `$(window)`, `$('body')`, only 1 will fire in each case. On the other side when `window` is being used, `body.scrollTop` should report 0 which should make it safe to add everywhere.

**Comment by Tofandel** [comment]
```
case C.POSITION_TOP:
	this._offset.top += (globalOffset + arrowOffset.height) * -1 + document.body.scrollTop;
```
This gives me the correct result in the fiddle I don't know if it would work with other use cases though

**Comment by wintercounter** [comment]
I'll add it and make a few tests.

**Comment by Tofandel** [comment]
Thanks, it would be the same with the other top offsets as well and a + document.body.scrollLeft for the left offsets

**Comment by wintercounter** [comment]
Unfortuanatelly it ruins the calculation when overflow-x is not being added (which is the proper way). I need to find a proper solution to determ if it's needed or not, because document.body.scrollTop is reporting the same in both cases which is not entirely true.

**Comment by wintercounter** [comment]
Found the solution, publishing the fix soon.

**Comment by wintercounter** [comment]
Fixed and released in 1.4.18.
https://github.com/wintercounter/Protip/commit/c11eef1306e5200ad3e611428a9153ffab01fa2e

**Comment by Tofandel** [comment]
Great, thanks!
PS: The travis build failed because of wrong git credentials ;)

**Comment by wintercounter** [comment]
Yeah, I know :) I'm removing Travis completely. I prefer to do it manually
with this environment. Maybe I'll update in the future.
