### ISSUE TITLE
protipTemplate

### ISSUE THREAD

**Issue by yunzhisun** [wintercounter/Protip#36]
could you give me an example of that? I have read the code, but I can't figure out

**Comment by wintercounter** [comment]
I'm on holidays now, I can give a moredetailed answer later. Check https://github.com/wintercounter/Protip/blob/master/src/Constants.js and the TEMPLATE_PROTIP property. There are some variables there. The arrow related stuff not needed, the rest is. Everything else in the markup can be custom.
