### ISSUE TITLE
How to retrieve title and other data attribute from protip instance?

### ISSUE THREAD

**Issue by royallife88** [wintercounter/Protip#49]
Hi,
How to retrieve title and other data attributes from protip instance on protipshow event.

```
$('.protip').on('protipshow', function(ItemInstance){
    console.log(ItemInstance.currentTarget.ptTitle, 'title');  //showing undefined
 });
```

**Comment by wintercounter** [comment]
I'm from phone now cannot try it, but you can try `ItemInstance.data.title` in the callback. Please note that this can differ based on how the tooltip was initiated.

**Comment by royallife88** [comment]
It did not worked. get error
`Cannot read properties of undefined (reading 'title')`

**Comment by wintercounter** [comment]
I think the docs need to be updated. The first parameter in the callback is the jQuery event object, the second is the item instance.

```js
$('.protip').on('protipshow', function(ev, ItemInstance){
    console.log(ItemInstance.data.title);
 });
```

Closing the thread, let me know if you still have problems and I reopen it.

**Comment by royallife88** [comment]
Thank you! it's working.
